# Generated by Django 5.1.3 on 2024-11-22 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_titel_chat_title_message_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['sequence_number']},
        ),
    ]
